//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Action Assets + Their Scripts/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Battlefield Control"",
            ""id"": ""cb864428-2e93-4af3-a4c7-510829912156"",
            ""actions"": [
                {
                    ""name"": ""TapSelect"",
                    ""type"": ""Value"",
                    ""id"": ""b84baae1-33c9-43ab-be22-ff92a65cafb2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7e69e035-d65a-4e09-b41f-f2bdc8c4c353"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TapSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Battlefield Control
        m_BattlefieldControl = asset.FindActionMap("Battlefield Control", throwIfNotFound: true);
        m_BattlefieldControl_TapSelect = m_BattlefieldControl.FindAction("TapSelect", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Battlefield Control
    private readonly InputActionMap m_BattlefieldControl;
    private IBattlefieldControlActions m_BattlefieldControlActionsCallbackInterface;
    private readonly InputAction m_BattlefieldControl_TapSelect;
    public struct BattlefieldControlActions
    {
        private @Controls m_Wrapper;
        public BattlefieldControlActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @TapSelect => m_Wrapper.m_BattlefieldControl_TapSelect;
        public InputActionMap Get() { return m_Wrapper.m_BattlefieldControl; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BattlefieldControlActions set) { return set.Get(); }
        public void SetCallbacks(IBattlefieldControlActions instance)
        {
            if (m_Wrapper.m_BattlefieldControlActionsCallbackInterface != null)
            {
                @TapSelect.started -= m_Wrapper.m_BattlefieldControlActionsCallbackInterface.OnTapSelect;
                @TapSelect.performed -= m_Wrapper.m_BattlefieldControlActionsCallbackInterface.OnTapSelect;
                @TapSelect.canceled -= m_Wrapper.m_BattlefieldControlActionsCallbackInterface.OnTapSelect;
            }
            m_Wrapper.m_BattlefieldControlActionsCallbackInterface = instance;
            if (instance != null)
            {
                @TapSelect.started += instance.OnTapSelect;
                @TapSelect.performed += instance.OnTapSelect;
                @TapSelect.canceled += instance.OnTapSelect;
            }
        }
    }
    public BattlefieldControlActions @BattlefieldControl => new BattlefieldControlActions(this);
    public interface IBattlefieldControlActions
    {
        void OnTapSelect(InputAction.CallbackContext context);
    }
}
